project_id = "kkefwggimxljvelqtcjs"

[functions.payhere-checkout]
verify_jwt = false

[functions.payhere-notify]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false
