import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ta";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// English translations
const en: Record<string, string> = {
  // Navigation
  "nav.home": "Home",
  "nav.halls": "Halls",
  "nav.bungalows": "Bungalows",
  "nav.services": "Services",
  "nav.menus": "Menus",
  "nav.about": "About",
  "nav.contact": "Contact",
  "nav.bookNow": "Book Now",
  "nav.tagline": "Traditional Wedding Venues",

  // Hero Section
  "hero.title": "Sacred Unions, Blessed Beginnings",
  "hero.subtitle": "Experience the grandeur of traditional weddings at our exquisite mandapams. Where ancient rituals meet modern elegance.",
  "hero.cta.book": "Book Your Muhurtham",
  "hero.cta.explore": "Explore Mandapams",
  "hero.stats.halls": "Sacred Halls",
  "hero.stats.guests": "Max Guests",
  "hero.stats.legacy": "Years Legacy",

  // Featured Halls
  "halls.featured.title": "Our Sacred Mandapams",
  "halls.featured.label": "Sacred Venues",
  "halls.featured.description": "Discover our collection of beautifully crafted wedding venues, each designed to create unforgettable celebrations.",
  "halls.viewAll": "View All Halls",
  "halls.viewDetails": "View Details",
  "halls.book": "Book",
  "halls.featured": "Featured",
  "halls.capacity": "Capacity",
  "halls.guests": "guests",
  "halls.ac": "AC",
  "halls.parking": "Parking",
  "halls.dining": "Dining",
  "halls.checkAvailability": "Check Availability",

  // Halls Page
  "halls.page.title": "Our Wedding Mandapams",
  "halls.page.subtitle": "Discover our collection of beautifully crafted traditional wedding venues, each designed to create unforgettable celebrations steeped in culture and elegance.",
  "halls.page.description": "From intimate gatherings to grand celebrations, find the perfect mandapam for your sacred union.",
  "halls.page.chooseSpace": "Choose Your Sacred Space",
  "halls.cta.subtitle": "Find Your Perfect Venue",
  "halls.cta.title": "Found Your Perfect",
  "halls.cta.highlight": "Mandapam",
  "halls.cta.description": "Begin your auspicious journey. Book a visit to experience our mandapams or select your muhurtham date.",
  "halls.cta.button": "Select Muhurtham Date",
  
  // Hall Detail Page
  "hallDetail.overview": "Overview",
  "hallDetail.features": "Key Features",
  "hallDetail.facilities": "Facilities",
  "hallDetail.washrooms": "Washrooms",
  "hallDetail.virundhu": "Virundhu Options",
  "hallDetail.virundhu.desc": "We offer authentic Jaffna cuisine including traditional banana leaf feast, breakfast, lunch, and dinner options with both vegetarian and non-vegetarian choices.",
  "hallDetail.viewMenu": "View Full Menu",
  "hallDetail.bookThis": "Book This",
  "hallDetail.bookThis.highlight": "Mandapam",
  "hallDetail.bookThis.desc": "Secure your auspicious muhurtham date at",
  "hallDetail.bookNow": "Book Now",
  "hallDetail.callInquire": "Call to Inquire",
  "hallDetail.location": "Location",
  "hallDetail.quickFacts": "Quick Facts",
  "hallDetail.capacity": "Capacity",
  "hallDetail.airConditioned": "Air Conditioned",
  "hallDetail.parking": "Parking",
  "hallDetail.parking.available": "Available",
  "hallDetail.parking.limited": "Limited",
  "hallDetail.yes": "Yes",
  "hallDetail.no": "No",
  "hallDetail.idealFor": "Ideal For",
  "hallDetail.officeHours": "Office Hours",
  "hallDetail.monFri": "Monday - Friday",
  "hallDetail.saturday": "Saturday",
  "hallDetail.sunday": "Sunday",
  "hallDetail.byAppointment": "By Appointment",
  "hallDetail.siteVisits": "Site visits available upon request",
  "hallDetail.facility.ac": "குளிரூட்டி (AC)",
  "hallDetail.facility.parking": "வாகன நிறுத்தம்",
  "hallDetail.facility.dining": "உணவு அரங்கு",
  "hallDetail.facility.stage": "மேடை",
  "hallDetail.facility.powerBackup": "மின் காப்பு",
  "hallDetail.facility.brideRoom": "மணப்பெண் அறை",
  "hallDetail.facility.groomRoom": "மணமகன் அறை",

  // Services Preview
  "services.title": "Premium Wedding Services",
  "services.subtitle": "Complete Solutions",
  "services.description": "From traditional rituals to modern celebrations, we offer comprehensive services to make your wedding truly memorable.",
  "services.viewAll": "View All Services",

  // Services Page
  "services.page.title": "Premium Wedding Services",
  "services.page.subtitle": "Comprehensive Solutions for Your Sacred Day",
  "services.page.description": "From traditional rituals to modern celebrations, we offer end-to-end services that make your special day truly memorable.",
  "services.whyChoose.title": "Why Choose Our Services",
  "services.whyChoose.experience": "Years of Experience",
  "services.whyChoose.events": "Events Completed",
  "services.whyChoose.satisfaction": "Client Satisfaction",
  "services.hero.tagline": "Complete Thirumana Seva",
  "services.hero.title": "Our",
  "services.hero.highlight": "Services",
  "services.hero.description": "Beyond sacred mandapams, we offer complete wedding solutions rooted in tradition, ensuring your celebration is blessed, seamless, and truly unforgettable.",
  "services.tab.all": "All Services",
  "services.tab.essential": "Essentials",
  "services.tab.premium": "Premium",
  "services.tab.addon": "Add-ons",
  "services.tab.all.desc": "Explore our complete range of wedding services",
  "services.tab.essential.desc": "Core services for your perfect wedding",
  "services.tab.premium.desc": "Luxury additions for an extraordinary celebration",
  "services.tab.addon.desc": "Extra touches to enhance your special day",
  "services.quickBrowse": "Quick Browse",
  "services.sacredServices": "Sacred Wedding Services",
  "services.hoverDiscover": "Hover over each card to discover the full range of features included",
  "services.whyChoose.sectionTitle": "Our Tradition of Excellence",
  "services.whyChoose.mainTitle": "Why Choose Our",
  "services.whyChoose.highlight": "Seva",
  "services.whyChoose.desc": "We bring together the finest artisans, priests, and professionals to ensure your sacred ceremony exceeds all expectations.",
  "services.stats.years": "Years of Seva",
  "services.stats.years.desc": "Over 15 years creating blessed celebrations",
  "services.stats.unions": "Sacred Unions",
  "services.stats.unions.desc": "Hundreds of couples trust our traditions",
  "services.stats.partners": "Expert Partners",
  "services.stats.partners.desc": "Premium vendors for every ritual",
  "services.cta.subtitle": "Complete Wedding Solutions",
  "services.cta.title": "Ready to Plan Your",
  "services.cta.highlight": "Sacred Union",
  "services.cta.description": "All our seva can be selected during the booking process. Begin your auspicious journey to create the perfect celebration package.",
  "services.cta.button": "Begin Sacred Booking",

  // Testimonials
  "testimonials.title": "Sacred Testimonials",
  "testimonials.subtitle": "Blessed Couples",

  // CTA Section
  "cta.title": "Begin Your Sacred Journey",
  "cta.subtitle": "Ready to Create Memories?",
  "cta.description": "Let us help you plan the wedding of your dreams. Our expert team is ready to make your special day truly unforgettable.",
  "cta.book": "Book Your Date",
  "cta.call": "Call Us Now",

  // About Page
  "about.title": "Our Sacred Story",
  "about.subtitle": "A Legacy of Celebrations",
  "about.description": "For over two decades, we have been the trusted custodians of South Indian wedding traditions, creating sacred spaces where families unite and new beginnings flourish.",
  "about.mission.title": "Our Mission",
  "about.mission.description": "To preserve and celebrate the rich traditions of South Indian weddings while providing world-class hospitality and services.",
  "about.vision.title": "Our Vision",
  "about.vision.description": "To be the most trusted name in traditional wedding venues, known for excellence, authenticity, and heartfelt service.",
  "about.journey.title": "Our Journey",
  "about.team.title": "Meet Our Team",
  "about.team.subtitle": "The People Behind Your Perfect Day",
  "about.heroTitle": "About",
  "about.heroHighlight": "Celebration Halls",
  "about.story.title": "Our",
  "about.story.highlight": "Story",
  "about.story.p1": "Celebration Halls began with a sacred vision: to create divine spaces where love stories unfold according to cherished Tamil Hindu traditions.",
  "about.story.p2": "What started as a single mandapam has grown into a collection of five stunning venues, each designed with devotion and blessed ambiance.",
  "about.story.p3": "Over the years, we've had the privilege of hosting thousands of thirumangalyam ceremonies, receptions, and sacred celebrations. Each union has deepened our understanding, making us guardians of tradition while embracing the joy of every couple's unique journey.",
  "about.journey.subtitle": "A Legacy of",
  "about.journey.highlight": "Sacred Celebrations",
  "about.journey.description": "From humble beginnings to becoming the region's premier wedding destination",
  "about.values.subtitle": "Our Sacred Values",
  "about.values.title": "Why Choose",
  "about.values.highlight": "Us",
  "about.values.description": "What sets us apart is our devotion to making your sacred day truly divine and memorable.",
  "about.values.excellence.title": "Divine Excellence",
  "about.values.excellence.desc": "Award-winning mandapams with traditional elegance",
  "about.values.team.title": "Devoted Team",
  "about.values.team.desc": "Experienced professionals honoring your traditions",
  "about.values.service.title": "Premium Seva",
  "about.values.service.desc": "Complete wedding solutions under one sacred roof",
  "about.values.personal.title": "Personal Touch",
  "about.values.personal.desc": "Customized experiences for every blessed couple",
  "about.stats.years": "Years of Seva",
  "about.stats.mandapams": "Sacred Mandapams",
  "about.stats.unions": "Blessed Unions",
  "about.stats.satisfaction": "Happy Couples",
  "about.team.description": "Dedicated professionals who make every celebration extraordinary",
  "about.promise.title": "Our Sacred",
  "about.promise.highlight": "Promise",
  "about.promise.item1": "Impeccable seva from first inquiry to muhurtham day",
  "about.promise.item2": "Flexible packages honoring your family traditions",
  "about.promise.item3": "Transparent pricing with no hidden costs",
  "about.promise.item4": "Premium vendors ensuring quality for every ritual",
  "about.promise.item5": "Dedicated event coordinator for your celebration",
  "about.promise.item6": "Backup systems for uninterrupted sacred ceremonies",
  "about.cta.title": "Let's Create Your",
  "about.cta.highlight": "Perfect Day",
  "about.cta.description": "We'd be honored to be part of your sacred celebration. Book a visit to see our mandapams or start planning your auspicious event today.",
  "about.cta.bookNow": "Book Now",
  "about.cta.contactUs": "Contact Us",

  // Contact Page
  "contact.title": "Get in Touch",
  "contact.subtitle": "We'd Love to Hear From You",
  "contact.description": "Have questions about our venues or services? We're here to help you plan your perfect celebration.",
  "contact.form.name": "Your Name",
  "contact.form.email": "Email Address",
  "contact.form.phone": "Phone Number",
  "contact.form.message": "Your Message",
  "contact.form.submit": "Send Message",
  "contact.info.address": "Address",
  "contact.info.phone": "Phone",
  "contact.info.email": "Email",
  "contact.info.hours": "Working Hours",
  "contact.faq.title": "Frequently Asked Questions",
  "contact.info.title": "Contact Information",
  "contact.form.title": "Send us a Message",
  "contact.form.progress": "Form Progress",
  "contact.form.success.title": "Message Sent!",
  "contact.form.success.desc": "We'll get back to you within 24 hours.",
  "contact.followUs": "Follow Us",
  "contact.whatsapp": "Chat with us on WhatsApp",
  "contact.findUs": "Find",
  "contact.findUs.highlight": "Us",
  "contact.getDirections": "Get Directions",

  // Menus Page
  "menus.title": "Traditional Feast Menus",
  "menus.subtitle": "Authentic South Indian Cuisine",
  "menus.description": "Delight your guests with our carefully curated menu packages featuring authentic South Indian delicacies prepared by master chefs.",
  "menus.veg": "Vegetarian",
  "menus.nonveg": "Non-Vegetarian",
  "menus.special": "Special Packages",
  "menus.packages": "packages",
  "menus.calculator.title": "Price Calculator",
  "menus.calculator.guests": "Number of Guests",
  "menus.calculator.estimate": "Estimated Price",
  "menus.pubert.title": "Pubert",
  "menus.pubert.highlight": "(Lunch)",
  "menus.pubert.packages": "Packages",
  "menus.pubert.desc": "Traditional afternoon feast selections",
  "menus.dinner.title": "Dinner",
  "menus.dinner.highlight": "Packages",
  "menus.dinner.desc": "Evening feast selections for your special occasions",
  "menus.wedding.title": "Wedding",
  "menus.wedding.highlight": "Packages",
  "menus.wedding.desc": "Grand feast selections for your special wedding day",
  "menus.registration.title": "Registration",
  "menus.registration.highlight": "Packages",
  "menus.registration.desc": "Perfect feast selections for wedding registrations",
  "menus.dietary.title": "Dietary",
  "menus.dietary.highlight": "Options",
  "menus.dietary.desc": "We honor all dietary traditions and requirements with respect.",
  "menus.dietary.veg.title": "சைவ உணவு (Vegetarian)",
  "menus.dietary.veg.desc": "Full vegetarian menu with pure sattvic options",
  "menus.dietary.nonveg.title": "அசைவம் (Non-Vegetarian)",
  "menus.dietary.nonveg.desc": "Premium Jaffna-style seafood and meat selections",
  "menus.cta.subtitle": "Customize Your Feast",
  "menus.cta.title": "Ready to Select Your",
  "menus.cta.highlight": "Menu Package",
  "menus.cta.description": "All menus can be customized to honor your family traditions and preferences. Our master cooks will work with you to create the perfect feast for your auspicious occasion.",
  "menus.cta.button": "Select Menu & Book",

  // Bungalows Page
  "bungalows.title": "Guest Bungalows",
  "bungalows.subtitle": "Comfortable Accommodations",
  "bungalows.description": "Provide your guests with comfortable and convenient stay options near our wedding venues.",
  "bungalows.perNight": "per night",
  "bungalows.maxOccupancy": "Max Occupancy",
  "bungalows.persons": "persons",
  "bungalows.viewDetails": "View Details",
  "bungalows.bookNow": "Book Now",
  "bungalows.available": "Available",
  "bungalows.notAvailable": "Not Available",

  // Booking Page
  "booking.title": "Book Your Celebration",
  "booking.subtitle": "Reserve Your Special Day",
  "booking.step.hall": "Select Hall",
  "booking.step.date": "Choose Date",
  "booking.step.event": "Event Details",
  "booking.step.menu": "Menu Selection",
  "booking.step.services": "Add Services",
  "booking.step.details": "Your Details",
  "booking.step.confirm": "Confirm",
  "booking.next": "Next",
  "booking.previous": "Previous",
  "booking.submit": "Submit Booking",
  "booking.success": "Booking Submitted Successfully!",
  "booking.success.message": "We will contact you shortly to confirm your reservation.",
  "booking.selectHall": "Select a Mandapam",
  "booking.selectHall.desc": "Select your preferred venue to see available dates",
  "booking.eventType": "Event Type",
  "booking.eventDate": "Event Date",
  "booking.eventDate.desc": "Dates with confirmed bookings or closures are unavailable",
  "booking.pickDate": "Pick a date",
  "booking.timeSlot": "Time Slot",
  "booking.guestCount": "Expected Guests",
  "booking.guestCount.placeholder": "Enter number of guests",
  "booking.selectMenu": "Select Menu Package",
  "booking.menuSection": "Menu Section",
  "booking.menuVariant": "Menu Type",
  "booking.selectMealType": "Select Meal Type",
  "booking.selectVariant": "Select Variant",
  "booking.selectPackage": "Select Package",
  "booking.menuNotes": "Special Requests / Dietary Requirements",
  "booking.menuNotes.placeholder": "Any special requests or dietary requirements...",
  "booking.addServices": "Additional Seva",
  "booking.addServices.desc": "Select any additional services you'd like to include",
  "booking.serviceNotes": "Special Notes for Services",
  "booking.serviceNotes.placeholder": "Any specific requirements for the selected services...",
  "booking.customerName": "Full Name",
  "booking.customerPhone": "Phone Number",
  "booking.customerEmail": "Email Address (Optional)",
  "booking.specialRequests": "Additional Message",
  "booking.specialRequests.placeholder": "Any other information you'd like to share...",
  "booking.yourDetails": "Your Details",
  "booking.back": "Back",
  "booking.submitSacred": "Sacred Booking",
  "booking.submitting": "Submitting...",
  "booking.submitted.title": "Booking Request Submitted!",
  "booking.submitted.shubham": "Shubham",
  "booking.submitted.reference": "Your Booking Reference",
  "booking.submitted.saveReference": "Please save this reference number to track your booking",
  "booking.submitted.thankYou": "Thank you for choosing our sacred mandapams. Our team will contact you within 24 hours to confirm your muhurtham details.",
  "booking.submitted.summary": "Booking Summary",
  "booking.submitted.reference.label": "Reference:",
  "booking.submitted.returnHome": "Return to Home",
  "booking.summary.eventType": "Event Type:",
  "booking.summary.date": "Date:",
  "booking.summary.timeSlot": "Time Slot:",
  "booking.summary.mandapam": "Mandapam:",
  "booking.summary.guests": "Guests:",
  "booking.summary.menu": "Menu:",
  "booking.summary.services": "Add-on Services:",
  "booking.event.wedding": "Wedding Ceremony",
  "booking.event.reception": "Wedding Reception",
  "booking.event.engagement": "Engagement",
  "booking.event.birthday": "Birthday Party",
  "booking.event.anniversary": "Anniversary",
  "booking.event.corporate": "Corporate Event",
  "booking.event.other": "Other",
  "booking.time.morning": "Morning (8:00 AM - 4:00 PM)",
  "booking.time.evening": "Evening (5:00 PM - 12:00 AM)",
  "booking.time.fullday": "Full Day (8:00 AM - 12:00 AM)",
  "booking.meal.breakfast": "Breakfast",
  "booking.meal.lunch": "Lunch",
  "booking.meal.dinner": "Dinner",
  "booking.service.photography": "Photography & Videography",
  "booking.service.vehicles": "Wedding Vehicles",
  "booking.service.decoration": "Decoration & Themes",
  "booking.service.soundLighting": "Sound & Lighting",
  "booking.service.coordination": "Event Coordination",
  "booking.service.djMusic": "DJ & Music",
  "booking.service.makeup": "Bridal Makeup",
  "booking.service.jewellery": "Jewellery",
  "booking.service.other": "Other Services",
  "booking.cta.subtitle": "Need Assistance?",
  "booking.cta.title": "Have Questions About Your",
  "booking.cta.highlight": "Booking",
  "booking.cta.description": "Our team is here to help you plan your perfect celebration. Reach out to us for personalized assistance.",
  "booking.cta.contact": "Contact Us",

  // Common
  "common.loading": "Loading...",
  "common.error": "Something went wrong",
  "common.retry": "Try Again",
  "common.close": "Close",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.search": "Search",
  "common.filter": "Filter",
  "common.all": "All",
  "common.viewMore": "View More",
  "common.learnMore": "Learn More",
  "common.readMore": "Read More",
  "common.seeAll": "See All",
  "common.perDay": "per day",
  "common.adults": "Adults",
  "common.children": "Children",
  "common.checkIn": "Check-in",
  "common.checkOut": "Check-out",
  "common.tariff": "Tariff Details",
  "common.amenities": "Features & Amenities",
  "common.rules": "Rules & Policies",

  // Footer
  "footer.about": "About Us",
  "footer.aboutText": "We are dedicated to creating unforgettable wedding experiences with our beautiful traditional venues and exceptional services.",
  "footer.quickLinks": "Quick Links",
  "footer.contact": "Contact Info",
  "footer.hours": "Working Hours",
  "footer.rights": "All rights reserved",
  "footer.tagline": "Creating Sacred Unions Since 2001",
};

// Tamil translations
const ta: Record<string, string> = {
  // Navigation - keeping English for nav items as per original commented code

  // Hero Section
  "hero.title": "திருமண பந்தம், மங்களகரமான தொடக்கம்",
  "hero.subtitle": "எமது நவீன பாரம்பரிய மண்டபங்களில் உங்கள் திருமண நிகழ்வை நடத்தி மகிழுங்கள்.",
  "hero.cta.book": "முகூர்த்தத்தை பதிவு செய்க",
  "hero.cta.explore": "மண்டபங்களைப் பார்க்க",
  "hero.stats.halls": "திருமண மண்டபங்கள்",
  "hero.stats.guests": "அதிகபட்ச விருந்தினர்",
  "hero.stats.legacy": "வருட மரபு",

  // Featured Halls
  "halls.featured.title": "உங்கள் கனவு திருமணத்திற்கான எங்கள் மண்டபங்கள்",
  "halls.featured.label": "புனித அரங்குகள்",
  "halls.featured.description": "வாழ்நாள் நினைவாக மாறும் உங்கள் திருமணத்தை சிறப்பாக்கும் எங்கள் அரங்கங்களை காணுங்கள்.",
  "halls.viewAll": "அனைத்தையும் காண்க",
  "halls.viewDetails": "விவரங்கள்",
  "halls.book": "முன்பதிவு",
  "halls.featured": "சிறப்பு",
  "halls.capacity": "கொள்ளளவு",
  "halls.guests": "விருந்தினர்",
  "halls.ac": "குளிரூட்டி",
  "halls.parking": "வாகன நிறுத்தம்",
  "halls.dining": "உணவு பகுதி",
  "halls.checkAvailability": "கிடைக்கும் தன்மை",

  // Halls Page
  "halls.page.title": "எங்கள் திருமண மண்டபங்கள்",
  "halls.page.subtitle": "கலாச்சாரம் மற்றும் நேர்த்தியுடன் வடிவமைக்கப்பட்ட பாரம்பரிய திருமண அரங்கங்கள்",
  "halls.page.description": "நெருக்கமான கூட்டங்கள் முதல் பெரிய கொண்டாட்டங்கள் வரை சரியான மண்டபத்தைக் கண்டறியுங்கள்.",
  "halls.page.chooseSpace": "உங்கள் வாழ்நாள் நினைவாக மாறும் இடத்தைத் தேர்வு செய்யுங்கள்",
  "halls.cta.subtitle": "உங்கள் சரியான அரங்கைக் கண்டறியுங்கள்",
  "halls.cta.title": "உங்கள் சரியான",
  "halls.cta.highlight": "மண்டபம்",
  "halls.cta.description": "உங்கள் மங்களகரமான பயணத்தைத் தொடங்குங்கள். எங்கள் மண்டபங்களைப் பார்க்க வருகை தரவும்.",
  "halls.cta.button": "முகூர்த்த தேதி தேர்வு",
  
  // Hall Detail Page
  "hallDetail.overview": "கண்ணோட்டம்",
  "hallDetail.features": "முக்கிய அம்சங்கள்",
  "hallDetail.facilities": "வசதிகள்",
  "hallDetail.washrooms": "கழிவறைகள்",
  "hallDetail.virundhu": "விருந்து விருப்பங்கள்",
  "hallDetail.virundhu.desc": "பாரம்பரிய வாழை இலை விருந்து, காலை உணவு, மதிய உணவு மற்றும் இரவு உணவு விருப்பங்களுடன் உண்மையான யாழ்ப்பாண உணவுகளை வழங்குகிறோம்.",
  "hallDetail.viewMenu": "முழு உணவு பட்டியல்",
  "hallDetail.bookThis": "இந்த மண்டபத்தை",
  "hallDetail.bookThis.highlight": "முன்பதிவு செய்க",
  "hallDetail.bookThis.desc": "இல் உங்கள் மங்களகரமான முகூர்த்த தேதியை ஒதுக்கவும்",
  "hallDetail.bookNow": "இப்போது முன்பதிவு",
  "hallDetail.callInquire": "விசாரிக்க அழைக்கவும்",
  "hallDetail.location": "இடம்",
  "hallDetail.quickFacts": "விரைவு தகவல்",
  "hallDetail.capacity": "கொள்ளளவு",
  "hallDetail.airConditioned": "குளிரூட்டி",
  "hallDetail.parking": "வாகன நிறுத்தம்",
  "hallDetail.parking.available": "கிடைக்கிறது",
  "hallDetail.parking.limited": "குறைவு",
  "hallDetail.yes": "ஆம்",
  "hallDetail.no": "இல்லை",
  "hallDetail.idealFor": "ஏற்றது",
  "hallDetail.officeHours": "அலுவலக நேரம்",
  "hallDetail.monFri": "திங்கள் - வெள்ளி",
  "hallDetail.saturday": "சனிக்கிழமை",
  "hallDetail.sunday": "ஞாயிறு",
  "hallDetail.byAppointment": "சந்திப்பின் மூலம்",
  "hallDetail.siteVisits": "கோரிக்கையின் பேரில் தள வருகை",
  "hallDetail.facility.ac": "குளிரூட்டி (AC)",
  "hallDetail.facility.parking": "வாகன நிறுத்தம்",
  "hallDetail.facility.dining": "உணவு அரங்கு",
  "hallDetail.facility.stage": "மேடை",
  "hallDetail.facility.powerBackup": "மின் காப்பு",
  "hallDetail.facility.brideRoom": "மணப்பெண் அறை",
  "hallDetail.facility.groomRoom": "மணமகன் அறை",

  // Services Preview
  "services.title": "உயர்தர திருமண சேவைகள்",
  "services.subtitle": "முழுமையான சேவைகள்",
  "services.description": "பாரம்பரிய சடங்குகள் முதல் நவீன கொண்டாட்டங்கள் வரை விரிவான சேவைகளை வழங்குகிறோம்.",
  "services.viewAll": "அனைத்து சேவைகள்",

  // Services Page
  "services.page.title": "உயர்தர திருமண சேவைகள்",
  "services.page.subtitle": "உங்கள் புனித நாளுக்கான விரிவான தீர்வுகள்",
  "services.page.description": "பாரம்பரிய சடங்குகள் முதல் நவீன கொண்டாட்டங்கள் வரை விரிவான சேவைகளை வழங்குகிறோம்.",
  "services.whyChoose.title": "எங்கள் சேவைகளை ஏன் தேர்வு செய்ய வேண்டும்",
  "services.whyChoose.experience": "ஆண்டுகள் அனுபவம்",
  "services.whyChoose.events": "நிகழ்வுகள் நிறைவு",
  "services.whyChoose.satisfaction": "வாடிக்கையாளர் திருப்தி",
  "services.hero.tagline": "முழுமையான திருமண சேவை",
  "services.hero.title": "எங்கள்",
  "services.hero.highlight": "சேவைகள்",
  "services.hero.description": "புனித மண்டபங்களுக்கு அப்பால், பாரம்பரியத்தில் வேரூன்றிய முழுமையான திருமண தீர்வுகளை வழங்குகிறோம்.",
  "services.tab.all": "அனைத்து சேவைகள்",
  "services.tab.essential": "அத்தியாவசியம்",
  "services.tab.premium": "பிரீமியம்",
  "services.tab.addon": "கூடுதல்",
  "services.tab.all.desc": "எங்கள் முழு சேவை வரம்பை ஆராயுங்கள்",
  "services.tab.essential.desc": "உங்கள் சிறந்த திருமணத்திற்கான முக்கிய சேவைகள்",
  "services.tab.premium.desc": "அசாதாரண கொண்டாட்டத்திற்கான சொகுசு சேர்த்தல்கள்",
  "services.tab.addon.desc": "உங்கள் சிறப்பு நாளை மேம்படுத்த கூடுதல் தொடுதல்கள்",
  "services.quickBrowse": "விரைவு பார்வை",
  "services.sacredServices": "புனித திருமண சேவைகள்",
  "services.hoverDiscover": "அம்சங்களைக் கண்டறிய ஒவ்வொரு அட்டையின் மீதும் நிறுத்துங்கள்",
  "services.whyChoose.sectionTitle": "எங்கள் சிறப்பின் பாரம்பரியம்",
  "services.whyChoose.mainTitle": "எங்கள் சேவையை ஏன்",
  "services.whyChoose.highlight": "தேர்வு செய்ய வேண்டும்",
  "services.whyChoose.desc": "சிறந்த கலைஞர்கள், புரோகிதர்கள் மற்றும் நிபுணர்களை ஒன்றிணைக்கிறோம்.",
  "services.stats.years": "சேவை ஆண்டுகள்",
  "services.stats.years.desc": "15+ ஆண்டுகள் ஆசீர்வதிக்கப்பட்ட கொண்டாட்டங்கள்",
  "services.stats.unions": "புனித திருமணங்கள்",
  "services.stats.unions.desc": "நூற்றுக்கணக்கான தம்பதிகள் நம்புகிறார்கள்",
  "services.stats.partners": "நிபுணர் பங்காளிகள்",
  "services.stats.partners.desc": "ஒவ்வொரு சடங்கிற்கும் உயர்தர விற்பனையாளர்கள்",
  "services.cta.subtitle": "முழுமையான திருமண தீர்வுகள்",
  "services.cta.title": "உங்கள் புனித திருமணத்தை",
  "services.cta.highlight": "திட்டமிடத் தயாரா",
  "services.cta.description": "எங்கள் அனைத்து சேவைகளையும் முன்பதிவு செயல்பாட்டின் போது தேர்ந்தெடுக்கலாம்.",
  "services.cta.button": "புனித முன்பதிவைத் தொடங்கு",

  // Testimonials
  "testimonials.title": "விருந்தினர் கருத்துகள்",
  "testimonials.subtitle": "ஆசீர்வதிக்கப்பட்ட தம்பதிகள்",

  // CTA Section
  "cta.title": "உங்கள் மகிழ்ச்சியான பயணத்தைத் தொடங்குங்கள்",
  "cta.subtitle": "சிறந்த தருணங்களை உருவாக்கத் தயாரா?",
  "cta.description": "உங்கள் கனவுக்குரிய திருமணத்தை திட்டமிட எங்கள் உதவியைப் பெறுங்கள்.",
  "cta.book": "தேதியை முன்பதிவு செய்க",
  "cta.call": "இப்போது அழைக்கவும்",

  // About Page
  "about.title": "எங்கள் புனித கதை",
  "about.subtitle": "கொண்டாட்டங்களின் மரபு",
  "about.description": "இரண்டு தசாப்தங்களுக்கும் மேலாக, தென்னிந்திய திருமண மரபுகளின் நம்பகமான பாதுகாவலர்களாக இருந்து வருகிறோம்.",
  "about.mission.title": "எங்கள் நோக்கம்",
  "about.mission.description": "தென்னிந்திய திருமணங்களின் வளமான மரபுகளைப் பாதுகாத்து கொண்டாடுவது.",
  "about.vision.title": "எங்கள் தொலைநோக்கு",
  "about.vision.description": "சிறப்பு, நம்பகத்தன்மை மற்றும் இதயபூர்வமான சேவைக்கு பெயர் பெற்ற பாரம்பரிய திருமண அரங்குகளில் மிகவும் நம்பகமான பெயராக இருப்பது.",
  "about.journey.title": "எங்கள் பயணம்",
  "about.team.title": "எங்கள் குழுவை சந்தியுங்கள்",
  "about.team.subtitle": "உங்கள் சரியான நாளுக்குப் பின்னால் உள்ள நபர்கள்",
  "about.heroTitle": "எங்களைப் பற்றி",
  "about.heroHighlight": "கொண்டாட்ட மண்டபங்கள்",
  "about.story.title": "எங்கள்",
  "about.story.highlight": "கதை",
  "about.story.p1": "கொண்டாட்ட மண்டபங்கள் ஒரு புனித நோக்கத்துடன் தொடங்கியது.",
  "about.story.p2": "ஒரு மண்டபமாக தொடங்கியது ஐந்து அழகான அரங்குகளின் தொகுப்பாக வளர்ந்துள்ளது.",
  "about.story.p3": "பல ஆண்டுகளாக, ஆயிரக்கணக்கான திருமங்கல்யம் சடங்குகளை நடத்தும் பெருமை எங்களுக்கு கிடைத்துள்ளது.",
  "about.journey.subtitle": "புனித கொண்டாட்டங்களின்",
  "about.journey.highlight": "மரபு",
  "about.journey.description": "தாழ்மையான தொடக்கங்களிலிருந்து பிராந்தியத்தின் முதன்மை திருமண இடமாக",
  "about.values.subtitle": "எங்கள் புனித மதிப்புகள்",
  "about.values.title": "எங்களை ஏன்",
  "about.values.highlight": "தேர்வு செய்ய வேண்டும்",
  "about.values.description": "உங்கள் புனித நாளை தெய்வீகமாகவும் மறக்க முடியாததாகவும் மாற்றுவது.",
  "about.values.excellence.title": "தெய்வீக சிறப்பு",
  "about.values.excellence.desc": "பாரம்பரிய நேர்த்தியுடன் விருது பெற்ற மண்டபங்கள்",
  "about.values.team.title": "அர்ப்பணிப்புள்ள குழு",
  "about.values.team.desc": "உங்கள் மரபுகளை மதிக்கும் அனுபவமிக்க நிபுணர்கள்",
  "about.values.service.title": "உயர்தர சேவை",
  "about.values.service.desc": "ஒரு புனித கூரையின் கீழ் முழுமையான திருமண தீர்வுகள்",
  "about.values.personal.title": "தனிப்பட்ட கவனிப்பு",
  "about.values.personal.desc": "ஒவ்வொரு தம்பதிக்கும் தனிப்பயனாக்கப்பட்ட அனுபவங்கள்",
  "about.stats.years": "சேவை ஆண்டுகள்",
  "about.stats.mandapams": "புனித மண்டபங்கள்",
  "about.stats.unions": "ஆசீர்வதிக்கப்பட்ட திருமணங்கள்",
  "about.stats.satisfaction": "மகிழ்ச்சியான தம்பதிகள்",
  "about.team.description": "ஒவ்வொரு கொண்டாட்டத்தையும் அசாதாரணமாக மாற்றும் நிபுணர்கள்",
  "about.promise.title": "எங்கள் புனித",
  "about.promise.highlight": "வாக்குறுதி",
  "about.promise.item1": "முதல் விசாரணை முதல் முகூர்த்த நாள் வரை குறைபாடற்ற சேவை",
  "about.promise.item2": "உங்கள் குடும்ப மரபுகளை மதிக்கும் நெகிழ்வான தொகுப்புகள்",
  "about.promise.item3": "மறைக்கப்பட்ட செலவுகள் இல்லாமல் வெளிப்படையான விலை நிர்ணயம்",
  "about.promise.item4": "ஒவ்வொரு சடங்கிற்கும் தரத்தை உறுதி செய்யும் உயர்தர விற்பனையாளர்கள்",
  "about.promise.item5": "உங்கள் கொண்டாட்டத்திற்கான அர்ப்பணிப்புள்ள நிகழ்வு ஒருங்கிணைப்பாளர்",
  "about.promise.item6": "தடையின்றி புனித சடங்குகளுக்கான காப்பு அமைப்புகள்",
  "about.cta.title": "உங்கள் சரியான நாளை",
  "about.cta.highlight": "உருவாக்குவோம்",
  "about.cta.description": "உங்கள் புனித கொண்டாட்டத்தின் ஒரு பகுதியாக இருப்பதில் நாங்கள் பெருமைப்படுவோம்.",
  "about.cta.bookNow": "இப்போது முன்பதிவு செய்க",
  "about.cta.contactUs": "தொடர்பு கொள்க",

  // Contact Page
  "contact.title": "தொடர்பில் இருங்கள்",
  "contact.subtitle": "உங்களிடமிருந்து கேட்க விரும்புகிறோம்",
  "contact.description": "எங்கள் அரங்குகள் அல்லது சேவைகள் பற்றி கேள்விகள் உள்ளதா? உங்களுக்கு உதவ நாங்கள் இங்கே இருக்கிறோம்.",
  "contact.form.name": "உங்கள் பெயர்",
  "contact.form.email": "மின்னஞ்சல் முகவரி",
  "contact.form.phone": "தொலைபேசி எண்",
  "contact.form.message": "உங்கள் செய்தி",
  "contact.form.submit": "செய்தி அனுப்பு",
  "contact.info.address": "முகவரி",
  "contact.info.phone": "தொலைபேசி",
  "contact.info.email": "மின்னஞ்சல்",
  "contact.info.hours": "வேலை நேரம்",
  "contact.faq.title": "அடிக்கடி கேட்கப்படும் கேள்விகள்",
  "contact.info.title": "தொடர்பு தகவல்",
  "contact.form.title": "செய்தி அனுப்புங்கள்",
  "contact.form.progress": "படிவ முன்னேற்றம்",
  "contact.form.success.title": "செய்தி அனுப்பப்பட்டது!",
  "contact.form.success.desc": "24 மணி நேரத்திற்குள் பதிலளிப்போம்.",
  "contact.followUs": "எங்களைப் பின்தொடருங்கள்",
  "contact.whatsapp": "WhatsApp-ல் தொடர்பு கொள்க",
  "contact.findUs": "எங்களைக்",
  "contact.findUs.highlight": "கண்டறியுங்கள்",
  "contact.getDirections": "வழிகாட்டுதல்",

  // Menus Page
  "menus.title": "பாரம்பரிய விருந்து உணவுகள்",
  "menus.subtitle": "உண்மையான தென்னிந்திய உணவு வகைகள்",
  "menus.description": "தலைசிறந்த சமையல் நிபுணர்களால் தயாரிக்கப்பட்ட உண்மையான தென்னிந்திய சுவைகள்.",
  "menus.veg": "சைவம்",
  "menus.nonveg": "அசைவம்",
  "menus.special": "சிறப்பு தொகுப்புகள்",
  "menus.packages": "தொகுப்புகள்",
  "menus.calculator.title": "விலை கணிப்பான்",
  "menus.calculator.guests": "விருந்தினர்களின் எண்ணிக்கை",
  "menus.calculator.estimate": "மதிப்பிடப்பட்ட விலை",
  "menus.pubert.title": "மதிய",
  "menus.pubert.highlight": "உணவு",
  "menus.pubert.packages": "தொகுப்புகள்",
  "menus.pubert.desc": "பாரம்பரிய மதிய விருந்து தேர்வுகள்",
  "menus.dinner.title": "இரவு",
  "menus.dinner.highlight": "உணவு தொகுப்புகள்",
  "menus.dinner.desc": "உங்கள் சிறப்பு நிகழ்வுகளுக்கான மாலை விருந்து",
  "menus.wedding.title": "திருமண",
  "menus.wedding.highlight": "தொகுப்புகள்",
  "menus.wedding.desc": "உங்கள் சிறப்பு திருமண நாளுக்கான பெரிய விருந்து",
  "menus.registration.title": "பதிவு",
  "menus.registration.highlight": "தொகுப்புகள்",
  "menus.registration.desc": "திருமண பதிவுக்கான சரியான விருந்து தேர்வுகள்",
  "menus.dietary.title": "உணவு",
  "menus.dietary.highlight": "விருப்பங்கள்",
  "menus.dietary.desc": "அனைத்து உணவு பாரம்பரியங்களையும் தேவைகளையும் மரியாதையுடன் மதிக்கிறோம்.",
  "menus.dietary.veg.title": "சைவ உணவு (Vegetarian)",
  "menus.dietary.veg.desc": "தூய சாத்வீக விருப்பங்களுடன் முழு சைவ உணவு",
  "menus.dietary.nonveg.title": "அசைவம் (Non-Vegetarian)",
  "menus.dietary.nonveg.desc": "உயர்தர யாழ்ப்பாண பாணி கடல் உணவுகள்",
  "menus.cta.subtitle": "உங்கள் விருந்தைத் தனிப்பயனாக்கு",
  "menus.cta.title": "உங்கள் உணவு தொகுப்பைத்",
  "menus.cta.highlight": "தேர்ந்தெடுக்கத் தயாரா",
  "menus.cta.description": "உங்கள் குடும்ப மரபுகளுக்கு ஏற்ப அனைத்து உணவுகளையும் தனிப்பயனாக்கலாம். எங்கள் சமையல் நிபுணர்கள் உங்களுடன் இணைந்து செயல்படுவார்கள்.",
  "menus.cta.button": "உணவு தேர்வு & முன்பதிவு",

  // Bungalows Page
  "bungalows.title": "விருந்தினர் இல்லங்கள்",
  "bungalows.subtitle": "வசதியான தங்குமிடங்கள்",
  "bungalows.description": "எங்கள் திருமண அரங்குகளுக்கு அருகில் வசதியான தங்கும் வாய்ப்புகள்.",
  "bungalows.perNight": "ஒரு இரவுக்கு",
  "bungalows.maxOccupancy": "அதிகபட்ச கொள்ளளவு",
  "bungalows.persons": "நபர்கள்",
  "bungalows.viewDetails": "விவரங்கள்",
  "bungalows.bookNow": "இப்போது முன்பதிவு",
  "bungalows.available": "கிடைக்கிறது",
  "bungalows.notAvailable": "கிடைக்கவில்லை",

  // Booking Page
  "booking.title": "உங்கள் கொண்டாட்டத்தை முன்பதிவு செய்க",
  "booking.subtitle": "உங்கள் சிறப்பு நாளை ஒதுக்கவும்",
  "booking.step.hall": "மண்டபம்",
  "booking.step.date": "தேதி",
  "booking.step.event": "நிகழ்வு",
  "booking.step.menu": "உணவு",
  "booking.step.services": "சேவைகள்",
  "booking.step.details": "விவரங்கள்",
  "booking.step.confirm": "உறுதி",
  "booking.next": "அடுத்து",
  "booking.previous": "முந்தைய",
  "booking.submit": "முன்பதிவு",
  "booking.success": "முன்பதிவு வெற்றி!",
  "booking.success.message": "உங்கள் ஒதுக்கீட்டை உறுதிப்படுத்த விரைவில் தொடர்புகொள்வோம்.",
  "booking.selectHall": "மண்டபத்தைத் தேர்வு",
  "booking.selectHall.desc": "கிடைக்கும் தேதிகளைக் காண அரங்கைத் தேர்வு செய்க",
  "booking.eventType": "நிகழ்வு வகை",
  "booking.eventDate": "நிகழ்வு தேதி",
  "booking.eventDate.desc": "உறுதிப்படுத்தப்பட்ட முன்பதிவு தேதிகள் கிடைக்காது",
  "booking.pickDate": "தேதியைத் தேர்வு",
  "booking.timeSlot": "நேர இடைவெளி",
  "booking.guestCount": "விருந்தினர் எண்ணிக்கை",
  "booking.guestCount.placeholder": "விருந்தினர்களின் எண்ணிக்கை",
  "booking.selectMenu": "உணவு தொகுப்பு",
  "booking.menuSection": "உணவு பிரிவு",
  "booking.menuVariant": "உணவு வகை",
  "booking.selectMealType": "உணவு வகையைத் தேர்வு",
  "booking.selectVariant": "வகையைத் தேர்வு",
  "booking.selectPackage": "தொகுப்பைத் தேர்வு",
  "booking.menuNotes": "சிறப்பு கோரிக்கைகள் / உணவு தேவைகள்",
  "booking.menuNotes.placeholder": "சிறப்பு கோரிக்கைகள் அல்லது உணவு தேவைகள்...",
  "booking.addServices": "கூடுதல் சேவை",
  "booking.addServices.desc": "சேர்க்க விரும்பும் சேவைகளைத் தேர்வு செய்க",
  "booking.serviceNotes": "சேவைகளுக்கான குறிப்புகள்",
  "booking.serviceNotes.placeholder": "தேர்ந்தெடுத்த சேவைகளுக்கான தேவைகள்...",
  "booking.customerName": "முழு பெயர்",
  "booking.customerPhone": "தொலைபேசி எண்",
  "booking.customerEmail": "மின்னஞ்சல் (விருப்பம்)",
  "booking.specialRequests": "கூடுதல் செய்தி",
  "booking.specialRequests.placeholder": "வேறு ஏதேனும் தகவல்...",
  "booking.yourDetails": "உங்கள் விவரங்கள்",
  "booking.back": "பின்",
  "booking.submitSacred": "புனித முன்பதிவு",
  "booking.submitting": "சமர்ப்பிக்கிறது...",
  "booking.submitted.title": "முன்பதிவு கோரிக்கை சமர்ப்பிக்கப்பட்டது!",
  "booking.submitted.shubham": "சுபம்",
  "booking.submitted.reference": "உங்கள் முன்பதிவு குறிப்பு",
  "booking.submitted.saveReference": "உங்கள் முன்பதிவைக் கண்காணிக்க இந்த எண்ணைச் சேமிக்கவும்",
  "booking.submitted.thankYou": "எங்கள் புனித மண்டபங்களைத் தேர்ந்தெடுத்ததற்கு நன்றி. 24 மணி நேரத்திற்குள் தொடர்புகொள்வோம்.",
  "booking.submitted.summary": "முன்பதிவு சுருக்கம்",
  "booking.submitted.reference.label": "குறிப்பு:",
  "booking.submitted.returnHome": "முகப்பிற்குத் திரும்பு",
  "booking.summary.eventType": "நிகழ்வு வகை:",
  "booking.summary.date": "தேதி:",
  "booking.summary.timeSlot": "நேரம்:",
  "booking.summary.mandapam": "மண்டபம்:",
  "booking.summary.guests": "விருந்தினர்:",
  "booking.summary.menu": "உணவு:",
  "booking.summary.services": "கூடுதல் சேவைகள்:",
  "booking.event.wedding": "திருமண விழா",
  "booking.event.reception": "திருமண வரவேற்பு",
  "booking.event.engagement": "நிச்சயதார்த்தம்",
  "booking.event.birthday": "பிறந்தநாள் விழா",
  "booking.event.anniversary": "திருமண நாள்",
  "booking.event.corporate": "நிறுவன நிகழ்வு",
  "booking.event.other": "மற்றவை",
  "booking.time.morning": "காலை (8:00 AM - 4:00 PM)",
  "booking.time.evening": "மாலை (5:00 PM - 12:00 AM)",
  "booking.time.fullday": "முழு நாள் (8:00 AM - 12:00 AM)",
  "booking.meal.breakfast": "காலை உணவு",
  "booking.meal.lunch": "மதிய உணவு",
  "booking.meal.dinner": "இரவு உணவு",
  "booking.service.photography": "புகைப்படம் & காணொளி",
  "booking.service.vehicles": "திருமண வாகனங்கள்",
  "booking.service.decoration": "அலங்காரம் & தீம்",
  "booking.service.soundLighting": "ஒலி & ஒளி",
  "booking.service.coordination": "நிகழ்வு ஒருங்கிணைப்பு",
  "booking.service.djMusic": "DJ & இசை",
  "booking.service.makeup": "மணமகள் அலங்காரம்",
  "booking.service.jewellery": "நகை",
  "booking.service.other": "பிற சேவைகள்",
  "booking.cta.subtitle": "உதவி தேவையா?",
  "booking.cta.title": "உங்கள் முன்பதிவு பற்றி",
  "booking.cta.highlight": "கேள்விகள் உள்ளதா",
  "booking.cta.description": "உங்கள் சிறந்த கொண்டாட்டத்தைத் திட்டமிட எங்கள் குழு உதவ தயாராக உள்ளது.",
  "booking.cta.contact": "தொடர்பு கொள்க",

  // Common
  "common.loading": "ஏற்றுகிறது...",
  "common.error": "ஏதோ தவறு நடந்துவிட்டது",
  "common.retry": "மீண்டும் முயற்சி",
  "common.close": "மூடு",
  "common.save": "சேமி",
  "common.cancel": "ரத்து",
  "common.search": "தேடு",
  "common.filter": "வடிகட்டு",
  "common.all": "அனைத்தும்",
  "common.viewMore": "மேலும் காண்க",
  "common.learnMore": "மேலும் அறிக",
  "common.readMore": "மேலும் படிக்க",
  "common.seeAll": "அனைத்தையும் காண்க",
  "common.perDay": "ஒரு நாளுக்கு",
  "common.adults": "பெரியவர்கள்",
  "common.children": "குழந்தைகள்",
  "common.checkIn": "உள்நுழைவு",
  "common.checkOut": "வெளியேறுதல்",
  "common.tariff": "கட்டண விவரங்கள்",
  "common.amenities": "வசதிகள் & சேவைகள்",
  "common.rules": "விதிகள் & கொள்கைகள்",
};

const translations: Record<Language, Record<string, string>> = { en, ta };

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
