-- Delete existing room data
DELETE FROM public.bungalow_rooms;

-- Insert 20 rooms with correct inventory
INSERT INTO public.bungalow_rooms (name, room_type, ac_type, max_adults, max_children, tariff_room_only, tariff_bb, tariff_full_board, amenities, rules, images, available, display_order, location, description, check_in_time, check_out_time) VALUES
-- Double Room AC (8 rooms)
('Double Room AC-1','Double Room','AC',2,1,6000,8000,12000,ARRAY['Air Conditioner','Attached Bathroom','Hot Water','TV','Wi-Fi','Parking','Housekeeping','Power Backup','Security'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800','https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800','https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800'],true,1,'East Wing','Comfortable air-conditioned double room with modern amenities.','12:00 PM','11:00 AM'),
('Double Room AC-2','Double Room','AC',2,1,6000,8000,12000,ARRAY['Air Conditioner','Attached Bathroom','Hot Water','TV','Wi-Fi','Parking','Housekeeping','Power Backup','Security'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],true,2,'East Wing','Comfortable air-conditioned double room with modern amenities.','12:00 PM','11:00 AM'),
('Double Room AC-3','Double Room','AC',2,1,6000,8000,12000,ARRAY['Air Conditioner','Attached Bathroom','Hot Water','TV','Wi-Fi','Parking','Housekeeping','Power Backup','Security'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],true,3,'East Wing','Comfortable air-conditioned double room with modern amenities.','12:00 PM','11:00 AM'),
('Double Room AC-4','Double Room','AC',2,1,6000,8000,12000,ARRAY['Air Conditioner','Attached Bathroom','Hot Water','TV','Wi-Fi','Parking','Housekeeping','Power Backup','Security'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],true,4,'East Wing','Comfortable air-conditioned double room with modern amenities.','12:00 PM','11:00 AM'),
('Double Room AC-5','Double Room','AC',2,1,6000,8000,12000,ARRAY['Air Conditioner','Attached Bathroom','Hot Water','TV','Wi-Fi','Parking','Housekeeping','Power Backup','Security'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],true,5,'East Wing','Comfortable air-conditioned double room with modern amenities.','12:00 PM','11:00 AM'),
('Double Room AC-6','Double Room','AC',2,1,6000,8000,12000,ARRAY['Air Conditioner','Attached Bathroom','Hot Water','TV','Wi-Fi','Parking','Housekeeping','Power Backup','Security'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],true,6,'East Wing','Comfortable air-conditioned double room with modern amenities.','12:00 PM','11:00 AM'),
('Double Room AC-7','Double Room','AC',2,1,6000,8000,12000,ARRAY['Air Conditioner','Attached Bathroom','Hot Water','TV','Wi-Fi','Parking','Housekeeping','Power Backup','Security'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],true,7,'East Wing','Comfortable air-conditioned double room with modern amenities.','12:00 PM','11:00 AM'),
('Double Room AC-8','Double Room','AC',2,1,6000,8000,12000,ARRAY['Air Conditioner','Attached Bathroom','Hot Water','TV','Wi-Fi','Parking','Housekeeping','Power Backup','Security'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],true,8,'East Wing','Comfortable air-conditioned double room with modern amenities.','12:00 PM','11:00 AM'),
-- Double Room Non-AC (4 rooms)
('Double Room Non-AC-1','Double Room','Non-AC',2,1,5000,8000,12000,ARRAY['Fan','Attached Bathroom','Hot Water','TV','Wi-Fi','Parking','Housekeeping','Power Backup','Security'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800'],true,9,'East Wing','Well-ventilated double room with ceiling fans and essential amenities.','12:00 PM','11:00 AM'),
('Double Room Non-AC-2','Double Room','Non-AC',2,1,5000,8000,12000,ARRAY['Fan','Attached Bathroom','Hot Water','TV','Wi-Fi','Parking','Housekeeping','Power Backup','Security'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800'],true,10,'East Wing','Well-ventilated double room with ceiling fans and essential amenities.','12:00 PM','11:00 AM'),
('Double Room Non-AC-3','Double Room','Non-AC',2,1,5000,8000,12000,ARRAY['Fan','Attached Bathroom','Hot Water','TV','Wi-Fi','Parking','Housekeeping','Power Backup','Security'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800'],true,11,'East Wing','Well-ventilated double room with ceiling fans and essential amenities.','12:00 PM','11:00 AM'),
('Double Room Non-AC-4','Double Room','Non-AC',2,1,5000,8000,12000,ARRAY['Fan','Attached Bathroom','Hot Water','TV','Wi-Fi','Parking','Housekeeping','Power Backup','Security'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800'],true,12,'East Wing','Well-ventilated double room with ceiling fans and essential amenities.','12:00 PM','11:00 AM'),
-- Triple Room AC (4 rooms)
('Triple Room AC-1','Triple Room','AC',3,1,9000,12000,18000,ARRAY['Air Conditioner','Attached Bathroom','Hot Water','TV','Wi-Fi','Parking','Housekeeping','Power Backup','Security','Refrigerator'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800'],true,13,'West Wing','Spacious air-conditioned triple room ideal for families.','12:00 PM','11:00 AM'),
('Triple Room AC-2','Triple Room','AC',3,1,9000,12000,18000,ARRAY['Air Conditioner','Attached Bathroom','Hot Water','TV','Wi-Fi','Parking','Housekeeping','Power Backup','Security','Refrigerator'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800'],true,14,'West Wing','Spacious air-conditioned triple room ideal for families.','12:00 PM','11:00 AM'),
('Triple Room AC-3','Triple Room','AC',3,1,9000,12000,18000,ARRAY['Air Conditioner','Attached Bathroom','Hot Water','TV','Wi-Fi','Parking','Housekeeping','Power Backup','Security','Refrigerator'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800'],true,15,'West Wing','Spacious air-conditioned triple room ideal for families.','12:00 PM','11:00 AM'),
('Triple Room AC-4','Triple Room','AC',3,1,9000,12000,18000,ARRAY['Air Conditioner','Attached Bathroom','Hot Water','TV','Wi-Fi','Parking','Housekeeping','Power Backup','Security','Refrigerator'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800'],true,16,'West Wing','Spacious air-conditioned triple room ideal for families.','12:00 PM','11:00 AM'),
-- Triple Room Non-AC (2 rooms)
('Triple Room Non-AC-1','Triple Room','Non-AC',3,1,8000,12000,18000,ARRAY['Fan','Attached Bathroom','Hot Water','TV','Wi-Fi','Parking','Housekeeping','Power Backup','Security'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800'],true,17,'West Wing','Comfortable non-AC triple room with natural ventilation.','12:00 PM','11:00 AM'),
('Triple Room Non-AC-2','Triple Room','Non-AC',3,1,8000,12000,18000,ARRAY['Fan','Attached Bathroom','Hot Water','TV','Wi-Fi','Parking','Housekeeping','Power Backup','Security'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800'],true,18,'West Wing','Comfortable non-AC triple room with natural ventilation.','12:00 PM','11:00 AM'),
-- Family Room AC (1 room)
('Family Room AC','Family Room','AC',4,1,12000,16000,24000,ARRAY['Air Conditioner','Attached Bathroom','Hot Water','TV','Wi-Fi','Kitchen Facility','Refrigerator','Parking','Housekeeping','Power Backup','Security','Living Room'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800'],true,19,'North Block','Premium air-conditioned family room with spacious living area.','12:00 PM','11:00 AM'),
-- Family Room Non-AC (1 room)
('Family Room Non-AC','Family Room','Non-AC',4,1,10000,16000,24000,ARRAY['Fan','Attached Bathroom','Hot Water','TV','Wi-Fi','Kitchen Facility','Refrigerator','Parking','Housekeeping','Power Backup','Security','Living Room'],ARRAY['Valid ID proof mandatory','Pets not allowed','Unmarried couples not allowed','No smoking inside rooms'],ARRAY['https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800'],true,20,'North Block','Spacious non-AC family room with excellent ventilation.','12:00 PM','11:00 AM');